sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t chinmaydeshmukh98/react-test -f ./client/Dockerfile.dev ./client
  # - docker build myOtherProject

script:
  - docker run -e CI=true chinmaydeshmukh98/react-test npm run test -- --coverage
  # - docker run myOtherProject

after_success:
  - docker build -t chinmaydeshmukh98/multi-client ./client
  - docker build -t chinmaydeshmukh98/multi-nginx ./nginx
  - docker build -t chinmaydeshmukh98/multi-server ./server
  - docker build -t chinmaydeshmukh98/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chinmaydeshmukh98/multi-client
  - docker push chinmaydeshmukh98/multi-nginx
  - docker push chinmaydeshmukh98/multi-server
  - docker push chinmaydeshmukh98/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-022340416766"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
